// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Cloud Pub/Sub API (pubsub/v1)
// Generated from:
//   Version: v1
//   Revision: 20181226
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.5
#ifndef  GOOGLE_PUBSUB_API_ACKNOWLEDGE_REQUEST_H_
#define  GOOGLE_PUBSUB_API_ACKNOWLEDGE_REQUEST_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_pubsub_api {
using namespace googleapis;

/**
 * Request for the Acknowledge method.
 *
 * @ingroup DataObject
 */
class AcknowledgeRequest : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static AcknowledgeRequest* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit AcknowledgeRequest(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit AcknowledgeRequest(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~AcknowledgeRequest();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_pubsub_api::AcknowledgeRequest</code>
   */
  const char* GetTypeName() const {
    return "google_pubsub_api::AcknowledgeRequest";
  }

  /**
   * Determine if the '<code>ackIds</code>' attribute was set.
   *
   * @return true if the '<code>ackIds</code>' attribute was set.
   */
  bool has_ack_ids() const {
    return Storage().isMember("ackIds");
  }

  /**
   * Clears the '<code>ackIds</code>' attribute.
   */
  void clear_ack_ids() {
    MutableStorage()->removeMember("ackIds");
  }


  /**
   * Get a reference to the value of the '<code>ackIds</code>' attribute.
   */
  const client::JsonCppArray<string > get_ack_ids() const {
     const Json::Value& storage = Storage("ackIds");
    return client::JsonValueToCppValueHelper<client::JsonCppArray<string > >(storage);
  }

  /**
   * Gets a reference to a mutable value of the '<code>ackIds</code>' property.
   *
   * The acknowledgment ID for the messages being acknowledged that was returned
   * by the Pub/Sub system in the `Pull` response. Must not be empty.
   *
   * @return The result can be modified to change the attribute value.
   */
  client::JsonCppArray<string > mutable_ackIds() {
    Json::Value* storage = MutableStorage("ackIds");
    return client::JsonValueToMutableCppValueHelper<client::JsonCppArray<string > >(storage);
  }

 private:
  void operator=(const AcknowledgeRequest&);
};  // AcknowledgeRequest
}  // namespace google_pubsub_api
#endif  // GOOGLE_PUBSUB_API_ACKNOWLEDGE_REQUEST_H_
