// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Cloud Pub/Sub API (pubsub/v1)
// Generated from:
//   Version: v1
//   Revision: 20181226
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.5
#ifndef  GOOGLE_PUBSUB_API_EXPIRATION_POLICY_H_
#define  GOOGLE_PUBSUB_API_EXPIRATION_POLICY_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_pubsub_api {
using namespace googleapis;

/**
 * A policy that specifies the conditions for resource expiration (i.e.,
 * automatic resource deletion).
 *
 * @ingroup DataObject
 */
class ExpirationPolicy : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static ExpirationPolicy* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ExpirationPolicy(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ExpirationPolicy(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~ExpirationPolicy();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_pubsub_api::ExpirationPolicy</code>
   */
  const char* GetTypeName() const {
    return "google_pubsub_api::ExpirationPolicy";
  }

  /**
   * Determine if the '<code>ttl</code>' attribute was set.
   *
   * @return true if the '<code>ttl</code>' attribute was set.
   */
  bool has_ttl() const {
    return Storage().isMember("ttl");
  }

  /**
   * Clears the '<code>ttl</code>' attribute.
   */
  void clear_ttl() {
    MutableStorage()->removeMember("ttl");
  }


  /**
   * Get the value of the '<code>ttl</code>' attribute.
   */
  const StringPiece get_ttl() const {
    const Json::Value& v = Storage("ttl");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>ttl</code>' attribute.
   *
   * Specifies the "time-to-live" duration for an associated resource. The
   * resource expires if it is not active for a period of `ttl`. The definition
   * of "activity" depends on the type of the associated resource. The minimum
   * and maximum allowed values for `ttl` depend on the type of the associated
   * resource, as well. If `ttl` is not set, the associated resource never
   * expires.
   *
   * @param[in] value The new value.
   */
  void set_ttl(const StringPiece& value) {
    *MutableStorage("ttl") = value.data();
  }

 private:
  void operator=(const ExpirationPolicy&);
};  // ExpirationPolicy
}  // namespace google_pubsub_api
#endif  // GOOGLE_PUBSUB_API_EXPIRATION_POLICY_H_
