// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Cloud Pub/Sub API (pubsub/v1)
// Generated from:
//   Version: v1
//   Revision: 20181226
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.5
#ifndef  GOOGLE_PUBSUB_API_LIST_SUBSCRIPTIONS_RESPONSE_H_
#define  GOOGLE_PUBSUB_API_LIST_SUBSCRIPTIONS_RESPONSE_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/pubsub_api/subscription.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_pubsub_api {
using namespace googleapis;

/**
 * Response for the `ListSubscriptions` method.
 *
 * @ingroup DataObject
 */
class ListSubscriptionsResponse : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static ListSubscriptionsResponse* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ListSubscriptionsResponse(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ListSubscriptionsResponse(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~ListSubscriptionsResponse();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_pubsub_api::ListSubscriptionsResponse</code>
   */
  const char* GetTypeName() const {
    return "google_pubsub_api::ListSubscriptionsResponse";
  }

  /**
   * Determine if the '<code>nextPageToken</code>' attribute was set.
   *
   * @return true if the '<code>nextPageToken</code>' attribute was set.
   */
  bool has_next_page_token() const {
    return Storage().isMember("nextPageToken");
  }

  /**
   * Clears the '<code>nextPageToken</code>' attribute.
   */
  void clear_next_page_token() {
    MutableStorage()->removeMember("nextPageToken");
  }


  /**
   * Get the value of the '<code>nextPageToken</code>' attribute.
   */
  const StringPiece get_next_page_token() const {
    const Json::Value& v = Storage("nextPageToken");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>nextPageToken</code>' attribute.
   *
   * If not empty, indicates that there may be more subscriptions that match
   * the request; this value should be passed in a new
   * `ListSubscriptionsRequest` to get more subscriptions.
   *
   * @param[in] value The new value.
   */
  void set_next_page_token(const StringPiece& value) {
    *MutableStorage("nextPageToken") = value.data();
  }

  /**
   * Determine if the '<code>subscriptions</code>' attribute was set.
   *
   * @return true if the '<code>subscriptions</code>' attribute was set.
   */
  bool has_subscriptions() const {
    return Storage().isMember("subscriptions");
  }

  /**
   * Clears the '<code>subscriptions</code>' attribute.
   */
  void clear_subscriptions() {
    MutableStorage()->removeMember("subscriptions");
  }


  /**
   * Get a reference to the value of the '<code>subscriptions</code>' attribute.
   */
  const client::JsonCppArray<Subscription > get_subscriptions() const;

  /**
   * Gets a reference to a mutable value of the '<code>subscriptions</code>'
   * property.
   *
   * The subscriptions that match the request.
   *
   * @return The result can be modified to change the attribute value.
   */
  client::JsonCppArray<Subscription > mutable_subscriptions();

 private:
  void operator=(const ListSubscriptionsResponse&);
};  // ListSubscriptionsResponse
}  // namespace google_pubsub_api
#endif  // GOOGLE_PUBSUB_API_LIST_SUBSCRIPTIONS_RESPONSE_H_
