// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Cloud Pub/Sub API (pubsub/v1)
// Generated from:
//   Version: v1
//   Revision: 20181226
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.5
#ifndef  GOOGLE_PUBSUB_API_PUBLISH_RESPONSE_H_
#define  GOOGLE_PUBSUB_API_PUBLISH_RESPONSE_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_pubsub_api {
using namespace googleapis;

/**
 * Response for the `Publish` method.
 *
 * @ingroup DataObject
 */
class PublishResponse : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static PublishResponse* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit PublishResponse(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit PublishResponse(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~PublishResponse();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_pubsub_api::PublishResponse</code>
   */
  const char* GetTypeName() const {
    return "google_pubsub_api::PublishResponse";
  }

  /**
   * Determine if the '<code>messageIds</code>' attribute was set.
   *
   * @return true if the '<code>messageIds</code>' attribute was set.
   */
  bool has_message_ids() const {
    return Storage().isMember("messageIds");
  }

  /**
   * Clears the '<code>messageIds</code>' attribute.
   */
  void clear_message_ids() {
    MutableStorage()->removeMember("messageIds");
  }


  /**
   * Get a reference to the value of the '<code>messageIds</code>' attribute.
   */
  const client::JsonCppArray<string > get_message_ids() const {
     const Json::Value& storage = Storage("messageIds");
    return client::JsonValueToCppValueHelper<client::JsonCppArray<string > >(storage);
  }

  /**
   * Gets a reference to a mutable value of the '<code>messageIds</code>'
   * property.
   *
   * The server-assigned ID of each published message, in the same order as
   * the messages in the request. IDs are guaranteed to be unique within
   * the topic.
   *
   * @return The result can be modified to change the attribute value.
   */
  client::JsonCppArray<string > mutable_messageIds() {
    Json::Value* storage = MutableStorage("messageIds");
    return client::JsonValueToMutableCppValueHelper<client::JsonCppArray<string > >(storage);
  }

 private:
  void operator=(const PublishResponse&);
};  // PublishResponse
}  // namespace google_pubsub_api
#endif  // GOOGLE_PUBSUB_API_PUBLISH_RESPONSE_H_
