// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.
// This code was generated by google-apis-code-generator 1.5.1

#ifndef  GOOGLE_PUBSUB_API_PUBSUB_API_H_
#define  GOOGLE_PUBSUB_API_PUBSUB_API_H_

#include "google/pubsub_api/acknowledge_request.h"
#include "google/pubsub_api/expr.h"
#include "google/pubsub_api/binding.h"
#include "google/pubsub_api/create_snapshot_request.h"
#include "google/pubsub_api/empty.h"
#include "google/pubsub_api/expiration_policy.h"
#include "google/pubsub_api/snapshot.h"
#include "google/pubsub_api/list_snapshots_response.h"
#include "google/pubsub_api/push_config.h"
#include "google/pubsub_api/subscription.h"
#include "google/pubsub_api/list_subscriptions_response.h"
#include "google/pubsub_api/list_topic_snapshots_response.h"
#include "google/pubsub_api/list_topic_subscriptions_response.h"
#include "google/pubsub_api/topic.h"
#include "google/pubsub_api/list_topics_response.h"
#include "google/pubsub_api/modify_ack_deadline_request.h"
#include "google/pubsub_api/modify_push_config_request.h"
#include "google/pubsub_api/policy.h"
#include "google/pubsub_api/pubsub_message.h"
#include "google/pubsub_api/publish_request.h"
#include "google/pubsub_api/publish_response.h"
#include "google/pubsub_api/pull_request.h"
#include "google/pubsub_api/received_message.h"
#include "google/pubsub_api/pull_response.h"
#include "google/pubsub_api/seek_request.h"
#include "google/pubsub_api/seek_response.h"
#include "google/pubsub_api/set_iam_policy_request.h"
#include "google/pubsub_api/test_iam_permissions_request.h"
#include "google/pubsub_api/test_iam_permissions_response.h"
#include "google/pubsub_api/update_snapshot_request.h"
#include "google/pubsub_api/update_subscription_request.h"
#include "google/pubsub_api/update_topic_request.h"

#include "google/pubsub_api/pubsub_service.h"


#endif  // GOOGLE_PUBSUB_API_PUBSUB_API_H_
