// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Cloud Pub/Sub API (pubsub/v1)
// Generated from:
//   Version: v1
//   Revision: 20181226
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.5
#ifndef  GOOGLE_PUBSUB_API_PULL_REQUEST_H_
#define  GOOGLE_PUBSUB_API_PULL_REQUEST_H_

#include "googleapis/base/integral_types.h"
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_pubsub_api {
using namespace googleapis;

/**
 * Request for the `Pull` method.
 *
 * @ingroup DataObject
 */
class PullRequest : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static PullRequest* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit PullRequest(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit PullRequest(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~PullRequest();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_pubsub_api::PullRequest</code>
   */
  const char* GetTypeName() const {
    return "google_pubsub_api::PullRequest";
  }

  /**
   * Determine if the '<code>maxMessages</code>' attribute was set.
   *
   * @return true if the '<code>maxMessages</code>' attribute was set.
   */
  bool has_max_messages() const {
    return Storage().isMember("maxMessages");
  }

  /**
   * Clears the '<code>maxMessages</code>' attribute.
   */
  void clear_max_messages() {
    MutableStorage()->removeMember("maxMessages");
  }


  /**
   * Get the value of the '<code>maxMessages</code>' attribute.
   */
  int32 get_max_messages() const {
    const Json::Value& storage = Storage("maxMessages");
    return client::JsonValueToCppValueHelper<int32 >(storage);
  }

  /**
   * Change the '<code>maxMessages</code>' attribute.
   *
   * The maximum number of messages returned for this request. The Pub/Sub
   * system may return fewer than the number specified.
   *
   * @param[in] value The new value.
   */
  void set_max_messages(int32 value) {
    client::SetJsonValueFromCppValueHelper<int32 >(
      value, MutableStorage("maxMessages"));
  }

  /**
   * Determine if the '<code>returnImmediately</code>' attribute was set.
   *
   * @return true if the '<code>returnImmediately</code>' attribute was set.
   */
  bool has_return_immediately() const {
    return Storage().isMember("returnImmediately");
  }

  /**
   * Clears the '<code>returnImmediately</code>' attribute.
   */
  void clear_return_immediately() {
    MutableStorage()->removeMember("returnImmediately");
  }


  /**
   * Get the value of the '<code>returnImmediately</code>' attribute.
   */
  bool get_return_immediately() const {
    const Json::Value& storage = Storage("returnImmediately");
    return client::JsonValueToCppValueHelper<bool >(storage);
  }

  /**
   * Change the '<code>returnImmediately</code>' attribute.
   *
   * If this field set to true, the system will respond immediately even if
   * it there are no messages available to return in the `Pull` response.
   * Otherwise, the system may wait (for a bounded amount of time) until at
   * least one message is available, rather than returning no messages.
   *
   * @param[in] value The new value.
   */
  void set_return_immediately(bool value) {
    client::SetJsonValueFromCppValueHelper<bool >(
      value, MutableStorage("returnImmediately"));
  }

 private:
  void operator=(const PullRequest&);
};  // PullRequest
}  // namespace google_pubsub_api
#endif  // GOOGLE_PUBSUB_API_PULL_REQUEST_H_
