// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Cloud Pub/Sub API (pubsub/v1)
// Generated from:
//   Version: v1
//   Revision: 20181226
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.5
#ifndef  GOOGLE_PUBSUB_API_RECEIVED_MESSAGE_H_
#define  GOOGLE_PUBSUB_API_RECEIVED_MESSAGE_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/pubsub_api/pubsub_message.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_pubsub_api {
using namespace googleapis;

/**
 * A message and its corresponding acknowledgment ID.
 *
 * @ingroup DataObject
 */
class ReceivedMessage : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static ReceivedMessage* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ReceivedMessage(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ReceivedMessage(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~ReceivedMessage();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_pubsub_api::ReceivedMessage</code>
   */
  const char* GetTypeName() const {
    return "google_pubsub_api::ReceivedMessage";
  }

  /**
   * Determine if the '<code>ackId</code>' attribute was set.
   *
   * @return true if the '<code>ackId</code>' attribute was set.
   */
  bool has_ack_id() const {
    return Storage().isMember("ackId");
  }

  /**
   * Clears the '<code>ackId</code>' attribute.
   */
  void clear_ack_id() {
    MutableStorage()->removeMember("ackId");
  }


  /**
   * Get the value of the '<code>ackId</code>' attribute.
   */
  const StringPiece get_ack_id() const {
    const Json::Value& v = Storage("ackId");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>ackId</code>' attribute.
   *
   * This ID can be used to acknowledge the received message.
   *
   * @param[in] value The new value.
   */
  void set_ack_id(const StringPiece& value) {
    *MutableStorage("ackId") = value.data();
  }

  /**
   * Determine if the '<code>message</code>' attribute was set.
   *
   * @return true if the '<code>message</code>' attribute was set.
   */
  bool has_message() const {
    return Storage().isMember("message");
  }

  /**
   * Clears the '<code>message</code>' attribute.
   */
  void clear_message() {
    MutableStorage()->removeMember("message");
  }


  /**
   * Get a reference to the value of the '<code>message</code>' attribute.
   */
  const PubsubMessage get_message() const;

  /**
   * Gets a reference to a mutable value of the '<code>message</code>' property.
   *
   * The message.
   *
   * @return The result can be modified to change the attribute value.
   */
  PubsubMessage mutable_message();

 private:
  void operator=(const ReceivedMessage&);
};  // ReceivedMessage
}  // namespace google_pubsub_api
#endif  // GOOGLE_PUBSUB_API_RECEIVED_MESSAGE_H_
