// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Cloud Pub/Sub API (pubsub/v1)
// Generated from:
//   Version: v1
//   Revision: 20181226
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.5
#ifndef  GOOGLE_PUBSUB_API_SNAPSHOT_H_
#define  GOOGLE_PUBSUB_API_SNAPSHOT_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_pubsub_api {
using namespace googleapis;

/**
 * A snapshot resource. Snapshots are used in
 * Seek
 * operations, which allow
 * you to manage message acknowledgments in bulk. That is, you can set the
 * acknowledgment state of messages in an existing subscription to the state
 * captured by a snapshot.
 * BETA: This feature is part of a beta release. This API might be
 * changed in backward-incompatible ways and is not recommended for production
 * use. It is not subject to any SLA or deprecation policy.
 *
 * @ingroup DataObject
 */
class Snapshot : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static Snapshot* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Snapshot(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Snapshot(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~Snapshot();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_pubsub_api::Snapshot</code>
   */
  const char* GetTypeName() const {
    return "google_pubsub_api::Snapshot";
  }

  /**
   * Determine if the '<code>expireTime</code>' attribute was set.
   *
   * @return true if the '<code>expireTime</code>' attribute was set.
   */
  bool has_expire_time() const {
    return Storage().isMember("expireTime");
  }

  /**
   * Clears the '<code>expireTime</code>' attribute.
   */
  void clear_expire_time() {
    MutableStorage()->removeMember("expireTime");
  }


  /**
   * Get the value of the '<code>expireTime</code>' attribute.
   */
  const StringPiece get_expire_time() const {
    const Json::Value& v = Storage("expireTime");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>expireTime</code>' attribute.
   *
   * The snapshot is guaranteed to exist up until this time.
   * A newly-created snapshot expires no later than 7 days from the time of its
   * creation. Its exact lifetime is determined at creation by the existing
   * backlog in the source subscription. Specifically, the lifetime of the
   * snapshot is `7 days - (age of oldest unacked message in the subscription)`.
   * For example, consider a subscription whose oldest unacked message is 3 days
   * old. If a snapshot is created from this subscription, the snapshot -- which
   * will always capture this 3-day-old backlog as long as the snapshot
   * exists -- will expire in 4 days. The service will refuse to create a
   * snapshot that would expire in less than 1 hour after creation.
   *
   * @param[in] value The new value.
   */
  void set_expire_time(const StringPiece& value) {
    *MutableStorage("expireTime") = value.data();
  }

  /**
   * Determine if the '<code>labels</code>' attribute was set.
   *
   * @return true if the '<code>labels</code>' attribute was set.
   */
  bool has_labels() const {
    return Storage().isMember("labels");
  }

  /**
   * Clears the '<code>labels</code>' attribute.
   */
  void clear_labels() {
    MutableStorage()->removeMember("labels");
  }


  /**
   * Get a reference to the value of the '<code>labels</code>' attribute.
   */
  const client::JsonCppAssociativeArray<string > get_labels() const {
     const Json::Value& storage = Storage("labels");
    return client::JsonValueToCppValueHelper<client::JsonCppAssociativeArray<string > >(storage);
  }

  /**
   * Gets a reference to a mutable value of the '<code>labels</code>' property.
   *
   * See  Creating and
   * managing labels.
   *
   * @return The result can be modified to change the attribute value.
   */
  client::JsonCppAssociativeArray<string > mutable_labels() {
    Json::Value* storage = MutableStorage("labels");
    return client::JsonValueToMutableCppValueHelper<client::JsonCppAssociativeArray<string > >(storage);
  }

  /**
   * Determine if the '<code>name</code>' attribute was set.
   *
   * @return true if the '<code>name</code>' attribute was set.
   */
  bool has_name() const {
    return Storage().isMember("name");
  }

  /**
   * Clears the '<code>name</code>' attribute.
   */
  void clear_name() {
    MutableStorage()->removeMember("name");
  }


  /**
   * Get the value of the '<code>name</code>' attribute.
   */
  const StringPiece get_name() const {
    const Json::Value& v = Storage("name");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>name</code>' attribute.
   *
   * The name of the snapshot.
   *
   * @param[in] value The new value.
   */
  void set_name(const StringPiece& value) {
    *MutableStorage("name") = value.data();
  }

  /**
   * Determine if the '<code>topic</code>' attribute was set.
   *
   * @return true if the '<code>topic</code>' attribute was set.
   */
  bool has_topic() const {
    return Storage().isMember("topic");
  }

  /**
   * Clears the '<code>topic</code>' attribute.
   */
  void clear_topic() {
    MutableStorage()->removeMember("topic");
  }


  /**
   * Get the value of the '<code>topic</code>' attribute.
   */
  const StringPiece get_topic() const {
    const Json::Value& v = Storage("topic");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>topic</code>' attribute.
   *
   * The name of the topic from which this snapshot is retaining messages.
   *
   * @param[in] value The new value.
   */
  void set_topic(const StringPiece& value) {
    *MutableStorage("topic") = value.data();
  }

 private:
  void operator=(const Snapshot&);
};  // Snapshot
}  // namespace google_pubsub_api
#endif  // GOOGLE_PUBSUB_API_SNAPSHOT_H_
