// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Cloud Pub/Sub API (pubsub/v1)
// Generated from:
//   Version: v1
//   Revision: 20181226
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.5
#ifndef  GOOGLE_PUBSUB_API_UPDATE_SNAPSHOT_REQUEST_H_
#define  GOOGLE_PUBSUB_API_UPDATE_SNAPSHOT_REQUEST_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/pubsub_api/snapshot.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_pubsub_api {
using namespace googleapis;

/**
 * Request for the UpdateSnapshot method.
 * BETA: This feature is part of a beta release. This API might be
 * changed in backward-incompatible ways and is not recommended for production
 * use. It is not subject to any SLA or deprecation policy.
 *
 * @ingroup DataObject
 */
class UpdateSnapshotRequest : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static UpdateSnapshotRequest* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit UpdateSnapshotRequest(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit UpdateSnapshotRequest(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~UpdateSnapshotRequest();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_pubsub_api::UpdateSnapshotRequest</code>
   */
  const char* GetTypeName() const {
    return "google_pubsub_api::UpdateSnapshotRequest";
  }

  /**
   * Determine if the '<code>snapshot</code>' attribute was set.
   *
   * @return true if the '<code>snapshot</code>' attribute was set.
   */
  bool has_snapshot() const {
    return Storage().isMember("snapshot");
  }

  /**
   * Clears the '<code>snapshot</code>' attribute.
   */
  void clear_snapshot() {
    MutableStorage()->removeMember("snapshot");
  }


  /**
   * Get a reference to the value of the '<code>snapshot</code>' attribute.
   */
  const Snapshot get_snapshot() const;

  /**
   * Gets a reference to a mutable value of the '<code>snapshot</code>'
   * property.
   *
   * The updated snapshot object.
   *
   * @return The result can be modified to change the attribute value.
   */
  Snapshot mutable_snapshot();

  /**
   * Determine if the '<code>updateMask</code>' attribute was set.
   *
   * @return true if the '<code>updateMask</code>' attribute was set.
   */
  bool has_update_mask() const {
    return Storage().isMember("updateMask");
  }

  /**
   * Clears the '<code>updateMask</code>' attribute.
   */
  void clear_update_mask() {
    MutableStorage()->removeMember("updateMask");
  }


  /**
   * Get the value of the '<code>updateMask</code>' attribute.
   */
  const StringPiece get_update_mask() const {
    const Json::Value& v = Storage("updateMask");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>updateMask</code>' attribute.
   *
   * Indicates which fields in the provided snapshot to update.
   * Must be specified and non-empty.
   *
   * @param[in] value The new value.
   */
  void set_update_mask(const StringPiece& value) {
    *MutableStorage("updateMask") = value.data();
  }

 private:
  void operator=(const UpdateSnapshotRequest&);
};  // UpdateSnapshotRequest
}  // namespace google_pubsub_api
#endif  // GOOGLE_PUBSUB_API_UPDATE_SNAPSHOT_REQUEST_H_
